[package]
name = "raknet"
version = "0.1.0"
authors = ["Göran Zachrisson <g.zachrisson@gmail.com>"]
edition = "2018"
license = "MIT"
description = "A RakNet library written in Rust"

[dependencies]
crossbeam-channel = "0.5"
log = "0.4"
rand = "0.7"